# Generated by Django 4.0.5 on 2022-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0010_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoo_notification',
            name='leave_apply_user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odoo_notification',
            name='leave_approve_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='odoo_notification',
            name='leave_type_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='odoo_notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_type', 'leave_type'), ('leave_approve_request', 'leave_approve_request')], max_length=255, null=True),
        ),
    ]
