# Generated by Django 4.0.5 on 2022-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0011_odoo_notification_leave_apply_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoo_notification',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
