# Generated by Django 4.0.5 on 2022-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0012_odoo_notification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoo_notification',
            name='current_leave_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
