# Generated by Django 4.0.5 on 2022-07-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0013_odoo_notification_current_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='fcm_token',
            field=models.TextField(null=True),
        ),
    ]
