# Generated by Django 4.0.5 on 2022-07-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0015_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_mapping_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(null=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
