# Generated by Django 4.0.5 on 2022-08-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0018_rename_leave_status_leave_status_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoo_notification',
            name='category',
            field=models.CharField(choices=[('notification', 'notification'), ('activities', 'activities')], max_length=255, null=True),
        ),
    ]
