# Generated by Django 4.0.5 on 2022-08-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0019_odoo_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='user_img',
            field=models.TextField(null=True),
        ),
    ]
