# Generated by Django 4.0.5 on 2022-08-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0024_test_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='pattern_lock_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_number', models.TextField(null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('auth_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_lock_user_login', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
