# Generated by Django 4.0.5 on 2022-08-12 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0025_pattern_lock_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_leave_draf_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=255, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('total_days', models.IntegerField(null=True)),
                ('reason', models.TextField(null=True)),
                ('alternative_contact_number', models.CharField(max_length=255, null=True)),
                ('employee_leave_replacer', models.IntegerField(null=True)),
                ('holiday_type', models.CharField(max_length=255, null=True)),
                ('employee_id', models.IntegerField(null=True)),
                ('request_unit_half', models.CharField(max_length=255, null=True)),
                ('request_date_form_period', models.CharField(max_length=255, null=True)),
                ('absence_status', models.CharField(max_length=255, null=True)),
                ('absence_category', models.CharField(max_length=255, null=True)),
                ('attached_file', models.FileField(null=True, upload_to='leave_attached_file')),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('auth_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_leave_draf_history_user_login', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_leave_draf_history_user_id', to='super_admin.user_management')),
            ],
        ),
    ]
