# Generated by Django 4.0.5 on 2022-08-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0026_user_leave_draf_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leave_draf_history',
            name='leave_type_id',
            field=models.IntegerField(null=True),
        ),
    ]
