# Generated by Django 4.0.5 on 2022-08-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0028_user_leave_draf_history_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leave_draf_history',
            name='employee_reg_number',
            field=models.IntegerField(null=True),
        ),
    ]
