# Generated by Django 4.0.5 on 2022-08-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0029_user_leave_draf_history_employee_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leave_draf_history',
            name='employee_replacer_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
