# Generated by Django 4.0.5 on 2022-08-17 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0031_login_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_otp',
            name='auth_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Login_otp_user_login', to=settings.AUTH_USER_MODEL),
        ),
    ]
