# Generated by Django 4.0.5 on 2022-08-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0032_login_otp_auth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_leave_draf_history',
            name='total_days',
            field=models.FloatField(null=True),
        ),
    ]
