# Generated by Django 4.0.5 on 2022-09-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0035_user_company_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_company_details',
            name='odoo_id',
            field=models.IntegerField(null=True),
        ),
    ]
