# Generated by Django 4.0.5 on 2022-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0036_user_company_details_odoo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoo_notification',
            name='petty_cash_apply_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odoo_notification',
            name='total_amount_with_currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='odoo_notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_type', 'leave_type'), ('leave_approve_request', 'leave_approve_request'), ('petty_cash_type', 'petty_cash_type')], max_length=255, null=True),
        ),
    ]
