# Generated by Django 4.0.5 on 2022-09-19 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0037_odoo_notification_petty_cash_apply_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='petty_cash_draft_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('employee_name', models.CharField(max_length=255, null=True)),
                ('expense_name', models.CharField(max_length=255, null=True)),
                ('payment_type', models.CharField(choices=[('Expense', 'Expense'), ('Supplier', 'Supplier')], max_length=255, null=True)),
                ('supplier', models.CharField(max_length=255, null=True)),
                ('employee_id', models.IntegerField(null=True)),
                ('supplier_id', models.IntegerField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('job_number', models.CharField(max_length=255, null=True)),
                ('auth_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_petty_cash_draft_history_user_login', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_petty_cash_draft_history_user_id', to='super_admin.user_management')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='petty_cash_expense_draft_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('expense_date', models.DateField(null=True)),
                ('product', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('partner', models.CharField(max_length=255, null=True)),
                ('reference', models.CharField(max_length=255, null=True)),
                ('unit_price', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('tax', models.CharField(max_length=255, null=True)),
                ('total_currency', models.CharField(max_length=255, null=True)),
                ('total', models.CharField(max_length=255, null=True)),
                ('product_id', models.CharField(max_length=255, null=True)),
                ('tax_id', models.CharField(max_length=255, null=True)),
                ('auth_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_expense_patty_cash_draft_history_user_id', to=settings.AUTH_USER_MODEL)),
                ('petty_cash_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_expense_patty_cash_draft_history_petty_cash_id', to='super_admin.petty_cash_draft_history')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_expense_patty_cash_draft_history_id', to='super_admin.user_management')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='petty_cash_attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('image_name', models.CharField(max_length=255, null=True)),
                ('image_value', models.TextField(null=True)),
                ('expense_petty_cash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_attachments', to='super_admin.petty_cash_expense_draft_history')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
