# Generated by Django 4.0.5 on 2022-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0038_petty_cash_draft_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petty_cash_expense_draft_history',
            name='expense_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
