# Generated by Django 4.0.5 on 2022-09-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0040_odoo_notification_expense_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petty_cash_draft_history',
            name='job_number',
        ),
        migrations.AddField(
            model_name='petty_cash_attachments',
            name='petty_cash_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_attachments', to='super_admin.petty_cash_draft_history'),
        ),
        migrations.AddField(
            model_name='petty_cash_expense_draft_history',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='petty_cash_expense_draft_history',
            name='job_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petty_cash_attachments',
            name='expense_petty_cash_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_petty_cash_attachments', to='super_admin.petty_cash_expense_draft_history'),
        ),
        migrations.AlterField(
            model_name='petty_cash_expense_draft_history',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='petty_cash_expense_draft_history',
            name='tax_id',
            field=models.IntegerField(null=True),
        ),
    ]
