# Generated by Django 4.0.5 on 2022-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0041_remove_petty_cash_draft_history_job_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petty_cash_expense_draft_history',
            name='job_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petty_cash_expense_draft_history',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petty_cash_expense_draft_history',
            name='tax_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
